module.exports = [
  {
    files: ["**/*.js"],
    ignores: ["tests/__snapshots__/**"],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: "script",
      globals: {
        window: "readonly",
        self: "readonly",
        document: "readonly",
        navigator: "readonly",
        localStorage: "readonly",
        AudioContext: "readonly",
        webkitAudioContext: "readonly",
        module: "readonly",
        require: "readonly",
        process: "readonly",
        global: "readonly",
        __dirname: "readonly",
        console: "readonly",
        setInterval: "readonly",
        clearInterval: "readonly",
        setTimeout: "readonly",
        clearTimeout: "readonly",
        Map: "readonly",
        Date: "readonly",
        JSON: "readonly",
        URL: "readonly",
        Promise: "readonly",
        caches: "readonly",
        fetch: "readonly",
        Response: "readonly",
        HTMLElement: "readonly",
        WebSocket: "readonly",
      },
    },
    rules: {
      "no-undef": "error",
      "no-unused-vars": ["warn", { "args": "none" }],
      "no-redeclare": "error",
      eqeqeq: ["error", "always", { "null": "ignore" }]
    },
  },
];
